version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\" "
      interval: 2s
      timeout: 20s
      retries: 10

  graphql-features-demo:
      restart: on-failure
      build: ./
      expose:
        - "8081"
      ports:
        - 8081:8081
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/mydatabase?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
        WAIT_HOSTS: mysql:3306
      depends_on:
        - docker-mysql
